In [1]:
!pip install keras_preprocessing

                                              0.0/42.6 kB ? eta -:--:--
     --------------------------------------   41.0/42.6 kB 2.0 MB/s eta 0:00:01
     -------------------------------------- 42.6/42.6 kB 414.6 kB/s eta 0:00:00


In [2]:
from keras_preprocessing.sequence import pad_sequences

In [3]:
!pip install keras

In [4]:
from keras.layers import Embedding, LSTM, Dense, Dropout
import numpy as np
import pandas as pd

In [5]:
from keras.preprocessing.text import Tokenizer

In [6]:
from keras.callbacks import EarlyStopping

In [7]:
from keras.models import Sequential

In [8]:
import keras.utils as ku

In [9]:
!pip install tensorflow

In [10]:
import tensorflow
tensorflow.random.set_seed(2)

In [11]:
import string, os 

In [12]:
import warnings
warnings.filterwarnings("ignore")
warnings.simplefilter(action='ignore', category=FutureWarning)

In [13]:

all_headlines = []
article_df = pd.read_csv('ArticlesApril2017.csv')
all_headlines.extend(list(article_df.headline.values))
all_headlines = [h for h in all_headlines if h != "Unknown"]
len(all_headlines)


831

In [14]:
len(article_df["headline"])

886

In [15]:
len(article_df["headline"].unique())

830

In [16]:
article_df["headline"].unique()

array(['Finding an Expansive View  of a Forgotten People in Niger',
       'And Now,  the Dreaded Trump Curse',
       'Venezuela’s Descent Into Dictatorship',
       'Stain Permeates Basketball Blue Blood',
       'Taking Things for Granted', 'The Caged Beast Awakens',
       'An Ever-Unfolding Story',
       'O’Reilly Thrives as Settlements Add Up', 'Mouse Infestation',
       'Divide in G.O.P. Now Threatens Trump Tax Plan',
       'Variety Puzzle: Acrostic',
       'They Can Hit a Ball 400 Feet. But Play Catch? That’s Tricky.',
       'In Trump Country, Shock at Trump Budget Cuts',
       'Why Is This Hate Different From All Other Hate?',
       'Pick Your Favorite Ethical Offender',
       'My Son’s Growing Black Pride',
       'Jerks and the Start-Ups They Ruin', 'Trump  Needs  a Brain',
       'Manhood in the Age of Trump', 'The Value of a Black College',
       'Initial Description', 'Rough Estimates', 'El Pasatiempo Nacional',
       'Cooling Off on a Hot Day at Yankee Stadium'

In [17]:
article_df

abstract                 articleID  articleWordCount  \
0        NaN  58def1347c459f24986d7c80               716   
1        NaN  58def3237c459f24986d7c84               823   
2        NaN  58def9f57c459f24986d7c90               575   
3        NaN  58defd317c459f24986d7c95              1374   
4        NaN  58df09b77c459f24986d7ca7               708   
..       ...                       ...               ...   
881      NaN  58fd41ab7c459f24986dbaa7               710   
882      NaN  58fd45a17c459f24986dbaaa              1230   
883      NaN  58fd5c2c7c459f24986dbac3              1424   
884      NaN  58fd5c3d7c459f24986dbac4              1052   
885      NaN  58fd5c3d7c459f24986dbac5               981   

                                     byline documentType  \
0       By STEPHEN HILTNER and SUSAN LEHMAN      article   
1                           By GAIL COLLINS      article   
2                    By THE EDITORIAL BOARD      article   
3                         By MICHAEL POWELL      article   
4                              By DEB AMLEN      article   
..                                      ...          ...   
881                     By ANDREW E. KRAMER      article   
882  By MATT FLEGENHEIMER and THOMAS KAPLAN      article   
883                          By NOEL MURRAY      article   
884                         By BEN BRANTLEY      article   
885                         By BEN BRANTLEY      article   

                                              headline  \
0    Finding an Expansive View  of a Forgotten Peop...   
1                    And Now,  the Dreaded Trump Curse   
2                Venezuela’s Descent Into Dictatorship   
3                Stain Permeates Basketball Blue Blood   
4                            Taking Things for Granted   
..                                                 ...   
881                Reporting on Gays Who ‘Don’t Exist’   
882  The Fights That Could Lead to a Government Shu...   
883  ‘The Leftovers’ Season 3, Episode 2: Swedish P...   
884                        Thinking Out Loud, But Why?   
885                  Some Sugar. Could Use More Spice.   

                                              keywords  multimedia    newDesk  \
0    ['Photography', 'New York Times', 'Niger', 'Fe...           3    Insider   
1    ['United States Politics and Government', 'Tru...           3       OpEd   
2    ['Venezuela', 'Politics and Government', 'Madu...           3  Editorial   
3    ['Basketball (College)', 'University of North ...           3     Sports   
4                                ['Crossword Puzzles']           3      Games   
..                                                 ...         ...        ...   
881  ['Chechnya (Russia)', 'Homosexuality and Bisex...           3    Insider   
882  ['Trump, Donald J', 'United States Politics an...           3   National   
883       ['Television', 'The Leftovers (TV Program)']           3    Culture   
884  ['Theater', 'The Antipodes (Play)', 'Baker, An...           3    Culture   
885  ['Theater', 'Charlie and the Chocolate Factory...           3    Culture   

     printPage              pubDate         sectionName  \
0            2  2017-04-01 00:15:41             Unknown   
1           23  2017-04-01 00:23:58             Unknown   
2           22  2017-04-01 00:53:06             Unknown   
3            1  2017-04-01 01:06:52  College Basketball   
4            0  2017-04-01 02:00:14             Unknown   
..         ...                  ...                 ...   
881          2  2017-04-24 00:07:04             Unknown   
882         15  2017-04-24 00:23:53            Politics   
883          0  2017-04-24 02:00:04          Television   
884          1  2017-04-24 02:00:25             Unknown   
885          2  2017-04-24 02:00:26             Unknown   

                                               snippet              source  \
0    One of the largest photo displays in Times his...  The New York Times   
1                    Meet t

In [18]:
all_headlines

['Finding an Expansive View  of a Forgotten People in Niger',
 'And Now,  the Dreaded Trump Curse',
 'Venezuela’s Descent Into Dictatorship',
 'Stain Permeates Basketball Blue Blood',
 'Taking Things for Granted',
 'The Caged Beast Awakens',
 'An Ever-Unfolding Story',
 'O’Reilly Thrives as Settlements Add Up',
 'Mouse Infestation',
 'Divide in G.O.P. Now Threatens Trump Tax Plan',
 'Variety Puzzle: Acrostic',
 'They Can Hit a Ball 400 Feet. But Play Catch? That’s Tricky.',
 'In Trump Country, Shock at Trump Budget Cuts',
 'Why Is This Hate Different From All Other Hate?',
 'Pick Your Favorite Ethical Offender',
 'My Son’s Growing Black Pride',
 'Jerks and the Start-Ups They Ruin',
 'Trump  Needs  a Brain',
 'Manhood in the Age of Trump',
 'The Value of a Black College',
 'Initial Description',
 'Rough Estimates',
 'El Pasatiempo Nacional',
 'Cooling Off on a Hot Day at Yankee Stadium',
 'Trump’s Staff Mixed Politics and Paydays',
 'A Virtuoso Rebuilding Act Requires Everyone in Tune',

In [19]:
def clean_text(txt):
    txt = "".join(v for v in txt if v not in string.punctuation).lower()
    txt = txt.encode("utf8").decode("ascii",'ignore')
    return txt 

corpus = [clean_text(x) for x in all_headlines]
corpus[:10]


['finding an expansive view  of a forgotten people in niger',
 'and now  the dreaded trump curse',
 'venezuelas descent into dictatorship',
 'stain permeates basketball blue blood',
 'taking things for granted',
 'the caged beast awakens',
 'an everunfolding story',
 'oreilly thrives as settlements add up',
 'mouse infestation',
 'divide in gop now threatens trump tax plan']

In [31]:
tokenizer = Tokenizer()

def get_sequence_of_tokens(corpus):
    ## tokenization
    tokenizer.fit_on_texts(corpus)
    total_words = len(tokenizer.word_index) + 1
    
    ## convert data to sequence of tokens 
    input_sequences = []
    for line in corpus:
        #print(line)
        #print(tokenizer.texts_to_sequences([line]))
        token_list = tokenizer.texts_to_sequences([line])[0]
        #print(token_list)
        for i in range(1, len(token_list)):
            n_gram_sequence = token_list[:i+1]
            input_sequences.append(n_gram_sequence)
    return input_sequences, total_words

inp_sequences, total_words = get_sequence_of_tokens(corpus)
inp_sequences[:10]

[[169, 17],
 [169, 17, 665],
 [169, 17, 665, 367],
 [169, 17, 665, 367, 4],
 [169, 17, 665, 367, 4, 2],
 [169, 17, 665, 367, 4, 2, 666],
 [169, 17, 665, 367, 4, 2, 666, 170],
 [169, 17, 665, 367, 4, 2, 666, 170, 5],
 [169, 17, 665, 367, 4, 2, 666, 170, 5, 667],
 [6, 80]]

In [40]:
def generate_padded_sequences(input_sequences):
    max_sequence_len = max([len(x) for x in input_sequences])
    input_sequences = np.array(pad_sequences(input_sequences, maxlen=max_sequence_len, padding='pre'))
    print(max_sequence_len)
    print(input_sequences)
    print("***** : ",input_sequences[:,:-1])
    print("########### : ",input_sequences[:,-1])
    print(len(input_sequences))
    print(len(input_sequences[0]))
    print(len(input_sequences[:,:-1])) # prints all rows and all columns expect last column
    print(len(input_sequences[:,-1])) #prints all rows but only last column
    predictors, label = input_sequences[:,:-1],input_sequences[:,-1]
    label = ku.to_categorical(label, num_classes=total_words)
    return predictors, label, max_sequence_len

predictors, label, max_sequence_len = generate_padded_sequences(inp_sequences)


19
[[   0    0    0 ...    0  169   17]
 [   0    0    0 ...  169   17  665]
 [   0    0    0 ...   17  665  367]
 ...
 [   0    0    0 ... 2420   57  365]
 [   0    0    0 ...   57  365   94]
 [   0    0    0 ...  365   94 2421]]
***** :  [[   0    0    0 ...    0    0  169]
 [   0    0    0 ...    0  169   17]
 [   0    0    0 ...  169   17  665]
 ...
 [   0    0    0 ...   96 2420   57]
 [   0    0    0 ... 2420   57  365]
 [   0    0    0 ...   57  365   94]]
########### :  [  17  665  367 ...  365   94 2421]
4806
19
4806
4806


In [45]:
print(predictors)
print(max_sequence_len)
label

[[   0    0    0 ...    0    0  169]
 [   0    0    0 ...    0  169   17]
 [   0    0    0 ...  169   17  665]
 ...
 [   0    0    0 ...   96 2420   57]
 [   0    0    0 ... 2420   57  365]
 [   0    0    0 ...   57  365   94]]
19


array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 1.]], dtype=float32)

In [41]:
def create_model(max_sequence_len, total_words):
    input_len = max_sequence_len - 1
    model = Sequential()
    
    # Add Input Embedding Layer
    model.add(Embedding(total_words, 10, input_length=input_len))
    
    # Add Hidden Layer 1 - LSTM Layer
    model.add(LSTM(100))
    model.add(Dropout(0.2))
        
    # Add Output Layer
    model.add(Dense(total_words, activation='softmax'))

    model.compile(loss='categorical_crossentropy', optimizer='adam')
    
    return model

model = create_model(max_sequence_len, total_words)
model.summary()




Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 18, 10)            24220     
                                                                 
 lstm (LSTM)                 (None, 100)               44400     
                                                                 
 dropout (Dropout)           (None, 100)               0         
                                                                 
 dense (Dense)               (None, 2422)              244622    
                                                                 
Total params: 313242 (1.19 MB)
Trainable params: 313242 (1.19 MB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [20]:
model.fit(predictors, label, epochs=100, verbose=2, batch_size=16)

Epoch 1/100
301/301 - 3s - loss: 7.3426 - 3s/epoch - 12ms/step
Epoch 2/100
301/301 - 2s - loss: 6.8823 - 2s/epoch - 6ms/step
Epoch 3/100
301/301 - 2s - loss: 6.7449 - 2s/epoch - 6ms/step
Epoch 4/100
301/301 - 2s - loss: 6.6286 - 2s/epoch - 6ms/step
Epoch 5/100
301/301 - 2s - loss: 6.4999 - 2s/epoch - 6ms/step
Epoch 6/100
301/301 - 2s - loss: 6.3511 - 2s/epoch - 6ms/step
Epoch 7/100
301/301 - 2s - loss: 6.2050 - 2s/epoch - 6ms/step
Epoch 8/100
301/301 - 2s - loss: 6.0269 - 2s/epoch - 6ms/step
Epoch 9/100
301/301 - 2s - loss: 5.8596 - 2s/epoch - 6ms/step
Epoch 10/100
301/301 - 2s - loss: 5.6851 - 2s/epoch - 6ms/step
Epoch 11/100
301/301 - 2s - loss: 5.5338 - 2s/epoch - 6ms/step
Epoch 12/100
301/301 - 2s - loss: 5.3733 - 2s/epoch - 6ms/step
Epoch 13/100
301/301 - 2s - loss: 5.2090 - 2s/epoch - 6ms/step
Epoch 14/100
301/301 - 2s - loss: 5.0741 - 2s/epoch - 6ms/step
Epoch 15/100
301/301 - 2s - loss: 4.9312 - 2s/epoch - 6ms/step
Epoch 16/100
301/301 - 2s - loss: 4.7957 - 2s/epoch - 6ms/step


In [21]:
def generate_text(seed_text, next_words, model, max_sequence_len):
    for _ in range(next_words):
        token_list = tokenizer.texts_to_sequences([seed_text])[0]
        token_list = pad_sequences([token_list], maxlen=max_sequence_len-1, padding='pre')
#predicted = model.predict_classes(token_list, verbose=0)
        predict_x=model.predict(token_list) 
        classes_x=np.argmax(predict_x,axis=1)

        output_word = ""
        for word,index in tokenizer.word_index.items():
            if index == classes_x:
                output_word = word
                break
        seed_text += " "+output_word
    return seed_text.title()


In [22]:
print (generate_text("united states", 5, model, max_sequence_len))
print (generate_text("president trump", 4, model, max_sequence_len))
print (generate_text("donald trump", 4, model, max_sequence_len))
print (generate_text("india and china", 4, model, max_sequence_len))
print (generate_text("new york", 4, model, max_sequence_len))
print (generate_text("science and technology", 5, model, max_sequence_len))

1/1 [==============================] - 0s 15ms/step
United States Soccer Team Wins More Not
1/1 [==============================] - 0s 15ms/step
President Trump Stolen Philosophys Critical Tools
1/1 [==============================] - 0s 15ms/step
Donald Trump A Tribal Identity Voting
1/1 [==============================] - 0s 15ms/step
India And China College Students On Its
1/1 [==============================] - 0s 17ms/step
New York Today A Holocaust Survivors
1/1 [==============================] - 0s 17ms/step
Science And Technology This Past Present Future On
