In [13]:
import pandas as pd
import numpy as np

In [14]:
df=pd.read_csv("final_all_names_code.csv")
df

Name Country_code Country
0                 Amy Johnson        ar_AE      AE
1               Thomas Wright        ar_AE      AE
2        Mr. Marco Flores DDS        ar_AE      AE
3              Marcus Robbins        ar_AE      AE
4            Susan Montgomery        ar_AE      AE
...                       ...          ...     ...
404057               Yang Lu         zh_TW      TW
404058              Liu Yuxin        zh_TW      TW
404059           Wu Wei Ting         zh_TW      TW
404060            Li Shuting         zh_TW      TW
404061             Sujiarong         zh_TW      TW

[404062 rows x 3 columns]

In [15]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 404062 entries, 0 to 404061
Data columns (total 3 columns):
 #   Column        Non-Null Count   Dtype 
---  ------        --------------   ----- 
 0   Name          404061 non-null  object
 1   Country_code  404062 non-null  object
 2   Country       404062 non-null  object
dtypes: object(3)
memory usage: 9.2+ MB


In [16]:
df.describe()

Name Country_code Country
count        404061       404062  404062
unique       404061           78      63
top     Amy Johnson        en_IE      TH
freq              1         6212   17326

In [17]:
df["Country"].unique()

array(['AE', 'EG', 'JO', 'PS', 'SA', 'AZ', 'BG', 'BD', 'BA', 'CZ', 'DK',
       'DE', 'AT', 'CH', 'CY', 'GR', 'AU', 'CA', 'GB', 'IE', 'IN', 'NZ',
       'PH', 'TH', 'US', 'ES', 'CO', 'MX', 'EE', 'IR', 'FI', 'FR', 'IL',
       'HR', 'HU', 'AM', 'ID', 'IT', 'JP', 'GE', 'KR', 'LA', 'LU', 'LT',
       'LV', 'MT', 'NP', 'BE', 'NL', 'NO', 'PL', 'BR', 'PT', 'RO', 'RU',
       'SK', 'SI', 'SE', 'TR', 'GH', 'UA', 'CN', 'TW'], dtype=object)

In [18]:
df[["Name","Country_code","Country"]]=df[["Name","Country_code","Country"]].astype("string")
df.dtypes

Name            string[python]
Country_code    string[python]
Country         string[python]
dtype: object

In [19]:
df.isnull().sum()

Name            1
Country_code    0
Country         0
dtype: int64

In [34]:
df.dtypes

Name            string[python]
Country_code    string[python]
Country         string[python]
dtype: object

In [20]:
df["Name"]=df['Name'].ffill()
df.isnull().sum()

Name            0
Country_code    0
Country         0
dtype: int64

In [21]:
df['Country'].unique()

<StringArray>
['AE', 'EG', 'JO', 'PS', 'SA', 'AZ', 'BG', 'BD', 'BA', 'CZ', 'DK', 'DE', 'AT',
 'CH', 'CY', 'GR', 'AU', 'CA', 'GB', 'IE', 'IN', 'NZ', 'PH', 'TH', 'US', 'ES',
 'CO', 'MX', 'EE', 'IR', 'FI', 'FR', 'IL', 'HR', 'HU', 'AM', 'ID', 'IT', 'JP',
 'GE', 'KR', 'LA', 'LU', 'LT', 'LV', 'MT', 'NP', 'BE', 'NL', 'NO', 'PL', 'BR',
 'PT', 'RO', 'RU', 'SK', 'SI', 'SE', 'TR', 'GH', 'UA', 'CN', 'TW']
Length: 63, dtype: string

In [22]:
df["Country"].nunique()

63

In [35]:
df["Country_code"].nunique()

78

In [27]:
data.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5913 entries, 0 to 5912
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Name          5913 non-null   string
 1   Country_code  5913 non-null   string
 2   Country       5913 non-null   string
dtypes: string(3)
memory usage: 184.8 KB


In [28]:
data1.info()

<class 'pandas.core.frame.DataFrame'>
Index: 5543 entries, 5913 to 11455
Data columns (total 3 columns):
 #   Column        Non-Null Count  Dtype 
---  ------        --------------  ----- 
 0   Name          5543 non-null   string
 1   Country_code  5543 non-null   string
 2   Country       5543 non-null   string
dtypes: string(3)
memory usage: 173.2 KB


In [32]:
#data=df[df["Country"]=='AE']
#data1=df[df["Country"]=='EG']
#data=data.append(data1,ignore_index=True)
data=df[(df["Country"]=='AE')|(df["Country"]=='EG')]
data             

Name Country_code Country
0                Amy Johnson        ar_AE      AE
1              Thomas Wright        ar_AE      AE
2       Mr. Marco Flores DDS        ar_AE      AE
3             Marcus Robbins        ar_AE      AE
4           Susan Montgomery        ar_AE      AE
...                      ...          ...     ...
11451     Joseph Christensen        ar_EG      EG
11452           Julia Cooper        ar_EG      EG
11453          Edward Turner        ar_EG      EG
11454        Edward Williams        ar_EG      EG
11455          Sabrina Hogan        ar_EG      EG

[11456 rows x 3 columns]

In [30]:
data


Name Country_code Country
0               Amy Johnson        ar_AE      AE
1             Thomas Wright        ar_AE      AE
2      Mr. Marco Flores DDS        ar_AE      AE
3            Marcus Robbins        ar_AE      AE
4          Susan Montgomery        ar_AE      AE
...                     ...          ...     ...
5908            Bob Wilkins        ar_AE      AE
5909           Carlos Riley        ar_AE      AE
5910       Christopher Hall        ar_AE      AE
5911          Crystal Lopez        ar_AE      AE
5912           David Carter        ar_AE      AE

[5913 rows x 3 columns]

In [36]:
data["Country"].unique()

<StringArray>
['AE', 'EG']
Length: 2, dtype: string

In [ ]:
surname=[]
for i in list(data["Name"]):
    l=i.split()
    surname.append(str(l[len(l)-1].lower()))
surname

['johnson',
 'wright',
 'dds',
 'robbins',
 'montgomery',
 'byrd',
 'watts',
 'morales',
 'davis',
 'wilson',
 'riley',
 'reid',
 'king',
 'chapman',
 'rodriguez',
 'park',
 'martin',
 'snyder',
 'andrews',
 'pitts',
 'obrien',
 'fleming',
 'cooper',
 'moore',
 'roberts',
 'mitchell',
 'jr.',
 'evans',
 'wise',
 'west',
 'ochoa',
 'gutierrez',
 'mckee',
 'phillips',
 'gomez',
 'richardson',
 'dixon',
 'phd',
 'jensen',
 'fisher',
 'pham',
 'sanders',
 'fitzpatrick',
 'johnson',
 'davis',
 'ritter',
 'alexander',
 'gray',
 'long',
 'love',
 'perkins',
 'krueger',
 'abbott',
 'cooper',
 'harris',
 'simmons',
 'evans',
 'gordon',
 'moore',
 'cannon',
 'flores',
 'mendoza',
 'allen',
 'downs',
 'keith',
 'harrison',
 'king',
 'fernandez',
 'vaughan',
 'klein',
 'collins',
 'smith',
 'diaz',
 'roach',
 'kelley',
 'moreno',
 'lambert',
 'powell',
 'carter',
 'huffman',
 'collins',
 'hall',
 'thompson',
 'butler',
 'rivas',
 'rios',
 'smith',
 'martin',
 'miles',
 'ramirez',
 'eaton',
 'garci

In [ ]:
data['Surname']=surname

In [ ]:
data

Name Country_code Country      Surname
0                Amy Johnson        ar_AE      AE      johnson
1              Thomas Wright        ar_AE      AE       wright
2       Mr. Marco Flores DDS        ar_AE      AE          dds
3             Marcus Robbins        ar_AE      AE      robbins
4           Susan Montgomery        ar_AE      AE   montgomery
...                      ...          ...     ...          ...
11451     Joseph Christensen        ar_EG      EG  christensen
11452           Julia Cooper        ar_EG      EG       cooper
11453          Edward Turner        ar_EG      EG       turner
11454        Edward Williams        ar_EG      EG     williams
11455          Sabrina Hogan        ar_EG      EG        hogan

[11456 rows x 4 columns]

In [ ]:
dic={}
column=['a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z',"Count","label"]
for i in column:
    dic[i]=[]

In [ ]:
for name in list(data["Surname"]):
    for i in column[:len(column)-2]:
        if i in name:
            dic[i].append(name.count(i))
        else:
            dic[i].append(0)
    dic['Count'].append(len(name))
    dic["label"].append('')

In [ ]:
dic

{'a': [0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  2,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  0,
  2,
  1,
  0,
  0,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  2,
  0,
  0,
  0,
  1,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  1,
  2,
  1,
  0,
  1,
  1,
  1,
  1,
  1,
  1,
  2,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  2,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  1,
  0,
  0,
  0,
  1,
  1,
  1,
  1,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  1,
  0,
  1,
  1,
  1,
  0,
  0,
  1,
  1,
  0,
  1,
  0,
  0,
  1,
  0,
  1,
  0,
  1,
  0,
  0,
  0,
  0,
  0,
  0,
  1,
  1,
  2,
  0,
  1,
  1,
  0,
  1,
  2,
  0,
  1,
  0,
  1,
  0,
  0,
  2,
  1,
  0,
  0,
  0,
  2,
  0,
  0,
  0,
  0,
  1,
  0,
  0,
  0,
  2,
  1,
  0,
  1,
  0,
  1,
  2,
  0,
  0,


In [ ]:
len(dic['a'])

11456

In [ ]:
dfff=pd.DataFrame(dic)
dfff

a  b  c  d  e  f  g  h  i  j  ...  s  t  u  v  w  x  y  z  Count  label
0      0  0  0  0  0  0  0  1  0  1  ...  1  0  0  0  0  0  0  0      7       
1      0  0  0  0  0  0  1  1  1  0  ...  0  1  0  0  1  0  0  0      6       
2      0  0  0  2  0  0  0  0  0  0  ...  1  0  0  0  0  0  0  0      3       
3      0  2  0  0  0  0  0  0  1  0  ...  1  0  0  0  0  0  0  0      7       
4      0  0  0  0  1  0  1  0  0  0  ...  0  1  0  0  0  0  1  0     10       
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. ..    ...    ...
11451  0  0  1  0  2  0  0  1  1  0  ...  2  1  0  0  0  0  0  0     11       
11452  0  0  1  0  1  0  0  0  0  0  ...  0  0  0  0  0  0  0  0      6       
11453  0  0  0  0  1  0  0  0  0  0  ...  0  1  1  0  0  0  0  0      6       
11454  1  0  0  0  0  0  0  0  2  0  ...  1  0  0  0  1  0  0  0      8       
11455  1  0  0  0  0  0  1  1  0  0  ...  0  0  0  0  0  0  0  0      5       

[11456 rows x 28 columns]

In [ ]:
dfff.iloc[0]

a        0
b        0
c        0
d        0
e        0
f        0
g        0
h        1
i        0
j        1
k        0
l        0
m        0
n        2
o        2
p        0
q        0
r        0
s        1
t        0
u        0
v        0
w        0
x        0
y        0
z        0
Count    7
label     
Name: 0, dtype: object

In [ ]:
dfff['Count'].unique()

array([ 7,  6,  3, 10,  4,  5,  9,  8, 11,  2,  1], dtype=int64)

In [ ]:
dfff['label']=data['Country']

In [ ]:
dfff

a  b  c  d  e  f  g  h  i  j  ...  s  t  u  v  w  x  y  z  Count  label
0      0  0  0  0  0  0  0  1  0  1  ...  1  0  0  0  0  0  0  0      7     AE
1      0  0  0  0  0  0  1  1  1  0  ...  0  1  0  0  1  0  0  0      6     AE
2      0  0  0  2  0  0  0  0  0  0  ...  1  0  0  0  0  0  0  0      3     AE
3      0  2  0  0  0  0  0  0  1  0  ...  1  0  0  0  0  0  0  0      7     AE
4      0  0  0  0  1  0  1  0  0  0  ...  0  1  0  0  0  0  1  0     10     AE
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. ..    ...    ...
11451  0  0  1  0  2  0  0  1  1  0  ...  2  1  0  0  0  0  0  0     11     EG
11452  0  0  1  0  1  0  0  0  0  0  ...  0  0  0  0  0  0  0  0      6     EG
11453  0  0  0  0  1  0  0  0  0  0  ...  0  1  1  0  0  0  0  0      6     EG
11454  1  0  0  0  0  0  0  0  2  0  ...  1  0  0  0  1  0  0  0      8     EG
11455  1  0  0  0  0  0  1  1  0  0  ...  0  0  0  0  0  0  0  0      5     EG

[11456 rows x 28 columns]

In [ ]:
dfff['label'].value_counts()

AE    5913
EG    5543
Name: label, dtype: Int64

In [ ]:
dfff['label'].unique()

<StringArray>
['AE', 'EG']
Length: 2, dtype: string

In [ ]:
x=dfff.drop(['label','Count'],axis=1)
y=dfff['label']

In [ ]:
x

a  b  c  d  e  f  g  h  i  j  ...  q  r  s  t  u  v  w  x  y  z
0      0  0  0  0  0  0  0  1  0  1  ...  0  0  1  0  0  0  0  0  0  0
1      0  0  0  0  0  0  1  1  1  0  ...  0  1  0  1  0  0  1  0  0  0
2      0  0  0  2  0  0  0  0  0  0  ...  0  0  1  0  0  0  0  0  0  0
3      0  2  0  0  0  0  0  0  1  0  ...  0  1  1  0  0  0  0  0  0  0
4      0  0  0  0  1  0  1  0  0  0  ...  0  1  0  1  0  0  0  0  1  0
...   .. .. .. .. .. .. .. .. .. ..  ... .. .. .. .. .. .. .. .. .. ..
11451  0  0  1  0  2  0  0  1  1  0  ...  0  1  2  1  0  0  0  0  0  0
11452  0  0  1  0  1  0  0  0  0  0  ...  0  1  0  0  0  0  0  0  0  0
11453  0  0  0  0  1  0  0  0  0  0  ...  0  2  0  1  1  0  0  0  0  0
11454  1  0  0  0  0  0  0  0  2  0  ...  0  0  1  0  0  0  1  0  0  0
11455  1  0  0  0  0  0  1  1  0  0  ...  0  0  0  0  0  0  0  0  0  0

[11456 rows x 26 columns]

In [ ]:
y

0        AE
1        AE
2        AE
3        AE
4        AE
         ..
11451    EG
11452    EG
11453    EG
11454    EG
11455    EG
Name: label, Length: 11456, dtype: string

In [ ]:
from sklearn.preprocessing import LabelEncoder

from sklearn.preprocessing import StandardScaler

In [ ]:

x = StandardScaler().fit_transform(x)
y = LabelEncoder().fit_transform(y)

In [ ]:
x

array([[-0.84869451, -0.35279648, -0.44309712, ..., -0.09663957,
        -0.33291289, -0.2948374 ],
       [-0.84869451, -0.35279648, -0.44309712, ..., -0.09663957,
        -0.33291289, -0.2948374 ],
       [-0.84869451, -0.35279648, -0.44309712, ..., -0.09663957,
        -0.33291289, -0.2948374 ],
       ...,
       [-0.84869451, -0.35279648, -0.44309712, ..., -0.09663957,
        -0.33291289, -0.2948374 ],
       [ 0.80989374, -0.35279648, -0.44309712, ..., -0.09663957,
        -0.33291289, -0.2948374 ],
       [ 0.80989374, -0.35279648, -0.44309712, ..., -0.09663957,
        -0.33291289, -0.2948374 ]])

In [ ]:
y

array([0, 0, 0, ..., 1, 1, 1])

In [ ]:
from keras.models import Sequential
from keras.layers import Dense
from sklearn.model_selection import train_test_split
from sklearn.neural_network import MLPClassifier
from sklearn.metrics import accuracy_score

In [ ]:
X_train, X_test, Y_train, Y_test = train_test_split(x,y, test_size=0.2, random_state=0)

In [ ]:
mlp_classifier = MLPClassifier(hidden_layer_sizes=(100,50,25), activation='relu',max_iter=25, random_state=42,verbose=1)
mlp_classifier.fit(X_train, Y_train)

# Predict on the test set
y_pred = mlp_classifier.predict(X_test)

# Evaluate accuracy
accuracy = accuracy_score(Y_test, y_pred)
print("Accuracy:", accuracy)

Iteration 1, loss = 0.69630413
Iteration 2, loss = 0.69009081
Iteration 3, loss = 0.68711957
Iteration 4, loss = 0.68519899
Iteration 5, loss = 0.68360703
Iteration 6, loss = 0.68175806
Iteration 7, loss = 0.68030759
Iteration 8, loss = 0.67896925
Iteration 9, loss = 0.67738216
Iteration 10, loss = 0.67581644
Iteration 11, loss = 0.67462097
Iteration 12, loss = 0.67360785
Iteration 13, loss = 0.67217357
Iteration 14, loss = 0.67116476
Iteration 15, loss = 0.66996053
Iteration 16, loss = 0.66788471
Iteration 17, loss = 0.66799833
Iteration 18, loss = 0.66749439
Iteration 19, loss = 0.66583935
Iteration 20, loss = 0.66375296
Iteration 21, loss = 0.66411527
Iteration 22, loss = 0.66269871
Iteration 23, loss = 0.66141715
Iteration 24, loss = 0.66129842
Iteration 25, loss = 0.65942402
Accuracy: 0.512216404886562


C:\Users\Shahana S\anaconda3\Lib\site-packages\sklearn\neural_network\_multilayer_perceptron.py:686: ConvergenceWarning: Stochastic Optimizer: Maximum iterations (25) reached and the optimization hasn't converged yet.
  warnings.warn(
